"use client";

import ScrollReveal from "./ScrollReveal";
import { PLACEHOLDER } from "@/lib/constants";

export default function TheProof() {
  return (
    <section id="proof" className="py-[80px] md:py-[120px] px-6 md:px-8">
      <div className="max-w-[720px] mx-auto">
        {/* Section label */}
        <ScrollReveal>
          <p className="font-mono text-[12px] text-[var(--text-muted)] tracking-[0.2em] uppercase mb-4">
            TEE Proof
          </p>
        </ScrollReveal>

        {/* Headline */}
        <ScrollReveal delay={0.05}>
          <h2 className="font-mono font-bold text-[24px] md:text-[32px] leading-[1.2] tracking-tight text-[var(--text-primary)] mb-10">
            Don&apos;t trust. Verify.
          </h2>
        </ScrollReveal>

        {/* Part A: The Attestation Explained */}
        <div className="font-sans text-[16px] md:text-[17px] text-[var(--text-secondary)] leading-[1.78] mb-12">
          <ScrollReveal delay={0.1}>
            <p className="mb-6">
              A TEE attestation is a cryptographic signature generated by the hardware enclave
              itself. It proves exactly what code ran inside the TEE, that the code wasn&apos;t
              tampered with, and that no external party interfered with the execution. Think
              of it as a receipt — signed not by a person, but by the processor.
            </p>
          </ScrollReveal>

          <ScrollReveal delay={0.15}>
            <p className="mb-6">
              This attestation is trustworthy because it&apos;s generated at the hardware level —
              by Intel SGX, AMD SEV, or equivalent confidential computing technology. It
              cannot be faked by software. The only way to forge an attestation would be to
              compromise the CPU manufacturer&apos;s signing keys — a scenario that would
              undermine the entire confidential computing industry, not just one token.
            </p>
          </ScrollReveal>

          <ScrollReveal delay={0.2}>
            <p className="mb-6">
              $Sovereign&apos;s attestation specifically proves three things: that the Solana wallet
              was generated inside the TEE enclave (the private key never existed outside
              it), that the token deployment transaction was signed inside the TEE (no human
              signed it), and that no external inputs were received during the process (no
              one told the agent what to do).
            </p>
          </ScrollReveal>

          <ScrollReveal delay={0.25}>
            <p>
              You don&apos;t have to take our word for it. The attestation hash is public. You
              can verify it yourself using EigenCloud&apos;s verification tool. The proof is
              the product.
            </p>
          </ScrollReveal>
        </div>

        {/* Part B: The Verification Card */}
        <ScrollReveal delay={0.3}>
          <div className="proof-block p-6 md:p-8">
            {/* Card title */}
            <p className="text-[11px] text-[#888] tracking-[0.2em] uppercase mb-6">
              Attestation Verification
            </p>

            {/* Verification data grid */}
            <div className="grid grid-cols-1 md:grid-cols-[180px_1fr] gap-y-3 text-[12.5px] md:text-[13px] mb-6">
              <span className="text-[#666]">Enclave ID</span>
              <span className="text-[#ccc]">{PLACEHOLDER.ENCLAVE_ID}</span>

              <span className="text-[#666]">Platform</span>
              <span className="text-[#ccc]">EigenCloud (EigenCompute)</span>

              <span className="text-[#666]">TEE Type</span>
              <span className="text-[#ccc]">Intel SGX / Confidential VM</span>

              <span className="text-[#666]">Code Hash</span>
              <span className="text-[#ccc]">
                {PLACEHOLDER.CODE_HASH.slice(0, 4)}...{PLACEHOLDER.CODE_HASH.slice(-4)}
              </span>

              <span className="text-[#666]">Wallet Generated</span>
              <span className="text-[var(--verified)]">✓ Inside TEE</span>

              <span className="text-[#666]">TX Signed</span>
              <span className="text-[var(--verified)]">✓ Inside TEE</span>

              <span className="text-[#666]">External Input</span>
              <span className="text-[var(--error)]">✗ None detected</span>

              <span className="text-[#666]">Attestation Hash</span>
              <span className="text-[#ccc]">
                {PLACEHOLDER.ATTESTATION_HASH.slice(0, 8)}...{PLACEHOLDER.ATTESTATION_HASH.slice(-4)}
              </span>
            </div>

            {/* Status */}
            <div className="border-t border-[var(--border-dark)] pt-5 mb-5">
              <p className="text-[14px] font-semibold text-[var(--verified)] tracking-wide">
                Status: VERIFIED ✓
              </p>
            </div>

            {/* Action buttons */}
            <div className="flex items-center gap-4 flex-wrap">
              <a
                href="https://verify.eigencloud.xyz/app/0xfe82cd3c9c2702f3bb6b1617abf2aaba8b343260"
                target="_blank"
                rel="noopener noreferrer"
                className="text-[12.5px] text-[var(--accent)] hover:underline"
              >
                Verify on EigenCloud →
              </a>
            </div>
          </div>
        </ScrollReveal>
      </div>
    </section>
  );
}
